#
# To deploy:
#
# kubectl apply -f scripts/deploy.yaml
#
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: history
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history
  template:
    metadata:
      labels:
        app: history
    spec:
      containers: 
      - name: history
        image: $CONTAINER_REGISTRY/history:1
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "4000"
        - name: DBHOST
          value: mongodb+srv://Sufi:Sufi777@cluster0.mmzbf.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
        - name: DBNAME
          value: history
        - name: RABBIT
          value:  amqp://guest:guest@localhost:5672/
---
apiVersion: v1
kind: Service
metadata:
  name: history
spec:
  selector:
    app: history
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
